App\Domain\Entity\Address:
  type: embeddable
  fields:
    street:
      type: string
      nullable: true
    zip:
      type: string
      nullable: true
    city:
      type: string
      nullable: true
    country:
      type: string
      nullable: true